---
name: Code checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-checks
  cancel-in-progress: true

jobs:
  plugin_test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test default
        uses: asdf-vm/actions/plugin-test@v3
        with:
          asdf_branch: v0.15.0
          command: k9s --help

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tools with asdf
        uses: asdf-vm/actions/install@v3
        with:
          asdf_branch: v0.15.0

      - name: Test plugin with bats
        run: |
          asdf plugin-add k9s "${GITHUB_WORKSPACE}"
          bats --filter-tags type:features --filter-tags type:os_specific test

  lint_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tools with asdf
        uses: asdf-vm/actions/install@v3
        with:
          asdf_branch: v0.15.0

      - uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit checks
        shell: bash
        run: |
          pre-commit run --all-files

      - name: Test code with bats
        run: |
          bats --filter-tags type:code test
